CREATE TABLE UGYFEL_MASKOLT
(
    LOGIN NVARCHAR(50) PRIMARY KEY,
    EMAIL NVARCHAR(100) NOT NULL MASKED WITH (FUNCTION = 'email()'),
    NEV NVARCHAR(100) NOT NULL MASKED WITH (FUNCTION = 'partial(2,"***")'),
    SZULEV INT,
    NEM NVARCHAR(10),
    CIM NVARCHAR(100) MASKED WITH (FUNCTION = 'random_address()')
);

INSERT INTO UGYFEL_MASKOLT (LOGIN, EMAIL, NEV, SZULEV, NEM, CIM)
SELECT
    LOGIN,
    SUBSTR(EMAIL, 1, 2) || '***@example.com',
    SUBSTR(NEV, 1, 2) || '***',
    SZULEV,
    NEM,
    CASE
        WHEN RANDOM() % 2 = 0 THEN 'Random utca 12.'
        ELSE 'Másik körút 45.'
    END
FROM UGYFEL;

CREATE USER MaskUser WITHOUT LOGIN;

GRANT SELECT ON UGYFEL_MASKOLT TO MaskUser;

EXECUTE AS USER = 'MaskUser';
SELECT * FROM UGYFEL_MASKOLT;
REVERT;